name: pocket_collection
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  get_it: ^8.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  provider: ^6.1.2
  intl: ^0.19.0
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/