import '../../../gen/assets.gen.dart';
import '../../domain/models/achievement_model.dart';

final List<AchievementModel> achievementData = [
  AchievementModel(
    id: 0,
    image: Assets.png.achievement1.path,
    dateTime: null,
    name: 'Add your first collection',
  ),
  AchievementModel(
    id: 1,
    image: Assets.png.achievement2.path,
    dateTime: null,
    name: 'Add 3 collections',
  ),
  AchievementModel(
    id: 2,
    image: Assets.png.achievement3.path,
    dateTime: null,
    name: 'Add 5 collections',
  ),
  AchievementModel(
    id: 3,
    image: Assets.png.achievement4.path,
    dateTime: null,
    name: 'Add 10 collections',
  ),
  AchievementModel(
    id: 4,
    image: Assets.png.achievement5.path,
    dateTime: null,
    name: 'Add 25 collections',
  ),
  AchievementModel(
    id: 5,
    image: Assets.png.achievement6.path,
    dateTime: null,
    name: 'Collect 10 items',
  ),
  AchievementModel(
    id: 6,
    image: Assets.png.achievement7.path,
    dateTime: null,
    name: 'Collect 30 items',
  ),
  AchievementModel(
    id: 7,
    image: Assets.png.achievement8.path,
    dateTime: null,
    name: 'Collect 50 items',
  ),
  AchievementModel(
    id: 8,
    image: Assets.png.achievement9.path,
    dateTime: null,
    name: 'Collect 75 items',
  ),
  AchievementModel(
    id: 9,
    image: Assets.png.achievement10.path,
    dateTime: null,
    name: 'Collect 100 items',
  ),
  AchievementModel(
    id: 10,
    image: Assets.png.achievement11.path,
    dateTime: null,
    name: 'Collect 250 items',
  ),
  AchievementModel(
    id: 11,
    image: Assets.png.achievement12.path,
    dateTime: null,
    name: 'Collect 500 items',
  ),
  AchievementModel(
    id: 12,
    image: Assets.png.achievement13.path,
    dateTime: null,
    name: 'Collect 1000 items',
  ),
  AchievementModel(
    id: 13,
    image: Assets.png.achievement14.path,
    dateTime: null,
    name: 'New week - new collection item',
  ),
  AchievementModel(
    id: 14,
    image: Assets.png.achievement15.path,
    dateTime: null,
    name: 'Have 3 different collections',
  ),
  AchievementModel(
    id: 15,
    image: Assets.png.achievement16.path,
    dateTime: null,
    name: 'Have 5 different collections',
  ),
  AchievementModel(
    id: 16,
    image: Assets.png.achievement17.path,
    dateTime: null,
    name: 'Have 10 different collections',
  ),
  AchievementModel(
    id: 17,
    image: Assets.png.achievement18.path,
    dateTime: null,
    name: 'Create a unique collection',
  ),
  AchievementModel(
    id: 18,
    image: Assets.png.achievement19.path,
    dateTime: null,
    name: 'Create 3 unique collections',
  ),
  AchievementModel(
    id: 19,
    image: Assets.png.achievement20.path,
    dateTime: null,
    name: 'Completely assembled collection',
  ),
  AchievementModel(
    id: 20,
    image: Assets.png.achievement21.path,
    dateTime: null,
    name: 'Collect 100 Rare items',
  ),
  AchievementModel(
    id: 21,
    image: Assets.png.achievement22.path,
    dateTime: null,
    name: 'Collect 50 Epic items',
  ),
  AchievementModel(
    id: 22,
    image: Assets.png.achievement23.path,
    dateTime: null,
    name: 'Collect 10 Legendary items',
  ),
  AchievementModel(
    id: 23,
    image: Assets.png.achievement24.path,
    dateTime: null,
    name: 'Add your Handbags',
  ),
  AchievementModel(
    id: 24,
    image: Assets.png.achievement25.path,
    dateTime: null,
    name: 'Collect 5 Handbags',
  ),
  AchievementModel(
    id: 25,
    image: Assets.png.achievement26.path,
    dateTime: null,
    name: 'Collect 20 Handbags',
  ),
  AchievementModel(
    id: 26,
    image: Assets.png.achievement27.path,
    dateTime: null,
    name: 'Collect 40 Handbags',
  ),
  AchievementModel(
    id: 27,
    image: Assets.png.achievement28.path,
    dateTime: null,
    name: 'Collect 80 Handbags',
  ),
  AchievementModel(
    id: 28,
    image: Assets.png.achievement29.path,
    dateTime: null,
    name: 'Create Coins & Currency collections',
  ),
  AchievementModel(
    id: 29,
    image: Assets.png.achievement30.path,
    dateTime: null,
    name: 'Create Books & Comics collections',
  ),
  AchievementModel(
    id: 30,
    image: Assets.png.achievement31.path,
    dateTime: null,
    name: 'Create Action Figures & Toy Cars collections',
  ),
  AchievementModel(
    id: 31,
    image: Assets.png.achievement32.path,
    dateTime: null,
    name: 'Create Vinyl Records & Music Instruments collections',
  ),
];
